### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ga-geymbukh** [denis5417/avito_parser#2]
Привет, пытаюсь запустить твой скрипт, выдает такую ошибку: 

```
Traceback (most recent call last):
  File "C:/Users/*/PycharmProjects/avito_parser/parts_parseer.py", line 3, in <module>
    for ad in get_all_ads('трактор мтз', sort_by='date', by_title=True):
  File "C:\Users\*\PycharmProjects\avito_parser\avito_parser.py", line 33, in get_all_ads
    yield agregate_ad_info(ad)
  File "C:\Users\*\PycharmProjects\avito_parser\avito_parser.py", line 57, in agregate_ad_info
    'Title': get_title(ad),
  File "C:\Users\*\PycharmProjects\avito_parser\avito_parser.py", line 65, in get_title
    return ad.find('a', attrs={'class': 'title-info-title-text'})['name']
TypeError: 'NoneType' object is not subscriptable
```
В чем может быть проблема?

**Comment by denis5417** [comment]
На сайте поменялась верстка, теперь атрибута с классом `'title-info-title-text'` там нет.
